#!/usr/bin/env bash

table=("$@")

quicksort()
{
    local low=$1
    local high=$2
    if ((low >= high)) ; then
        return
    fi
    local pivot=$(((table[low]+table[high])/2))
    local i=$low
    local j=$high
    while ((i < j)) ; do
        if ((table[i] <= pivot)) ; then
            ((i += 1))
        elif ((table[j] > pivot)) ; then
            ((j -= 1))
        elif ((i < j)) ; then
            local tmp=${table[$i]}
            table[$i]=${table[$j]}
            table[$j]=$tmp
        fi
    done
    quicksort $low $((i-1))
    quicksort $i $high
}

declare -A ahits=()
ahits+=([1:1]="00" [1:2]="00 01 02 02 03 05" [1:3]="03")
ahits+=([2:1]="15" [2:2]="06 07 08 09 10 11" [2:3]="06")
ahits+=([3:1]="02" [3:2]="12 13 14 15 16 17" [3:3]="09")
declare -p ahits

quicksort 0 $((${#ahits[*]} - 1))
printf "%s\n" "${ahits[*]}"

